apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: mqtt-influxdb
    url: http://influxdb:8086
    access: proxy
    isDefault: true
    editable: false
    jsonData:
      version: Flux
      organization: mqtt_org
      defaultBucket: camera_events
      tlsSkipVerify: true
    secureJsonData:
      token: mqtt-pipeline-secret-token
